<?php
# Autogenerated for testing

define('TR_CORE_SAVE','XXXXXXX');
define('TR_CORE_CANCEL','XXXXXXX');
define('TR_CORE_ASCENDING','XXXXXXX');
define('TR_CORE_DESCENDING','XXXXXXX');
define('TR_CORE_LEFT','XXXXXXX');
define('TR_CORE_RIGHT','XXXXXXX');
define('TR_CORE_CENTER','XXXXXXX');

?>
