<?php

if (!defined('PATHOS')) exit('');

return array(
	array(
		'name'=>'autoloader',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'core',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'config',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'database',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'flow',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'forms',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'files',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'info',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'modules',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'permissions',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'template',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'theme',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'sessions',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'sorting',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'users',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	array(
		'name'=>'workflow',
		'type'=>CORE_EXT_SUBSYSTEM,
		'comment'=>''
	),
	
	// Modules
	array(
		'name'=>'administrationmodule',
		'type'=>CORE_EXT_MODULE,
		'comment'=>''
	),
	array(
		'name'=>'common',
		'type'=>CORE_EXT_MODULE,
		'comment'=>''
	),
	array(
		'name'=>'workflow',
		'type'=>CORE_EXT_MODULE,
		'comment'=>''
	),
	array(
		'name'=>'filemanager',
		'type'=>CORE_EXT_MODULE,
		'comment'=>''
	),
	array(
		'name'=>'info',
		'type'=>CORE_EXT_MODULE,
		'comment'=>''
	),
	
	array(
		'name'=>'portaltheme',
		'type'=>CORE_EXT_THEME,
		'comment'=>''
	)
);

?>
