<?php

define("DB_ENGINE",'mysql');
define("DB_NAME",'alphadc');
define("DB_USER",'developer');
define("DB_PASS",'oicadmin42!');
define("DB_HOST",'devo');
define("DB_PORT",'3306');
define("DB_TABLE_PREFIX",'exponent');
define("DB_ENCODING",'utf8');
define("ORGANIZATION_NAME",'');
define("SITE_TITLE",'My New Exponent Site');
define("USE_LANG",'eng_US');
define("SITE_KEYWORDS",'');
define("SITE_DESCRIPTION",'');
define("SITE_404_HTML",exponent_unhtmlentities('&lt;h3&gt;Resource Not Found&lt;/h3&gt;<br />&lt;p&gt;The resource you were looking for wasn&#039;t found.  It may have been deleted, or moved.&amp;nbsp;&lt;/p&gt;'));
define("SITE_403_REAL_HTML",exponent_unhtmlentities('&lt;h3&gt;Authorization Failed&lt;/h3&gt;<br />&lt;p&gt;You are not allowed to perform this operation.&lt;/p&gt;'));
define("SITE_DEFAULT_SECTION",'1');
define("SITE_WYSIWYG_EDITOR",'FCKeditor');
define("SESSION_TIMEOUT",3600*5);
define("SESSION_TIMEOUT_HTML",exponent_unhtmlentities('&lt;h3&gt;Expired Login Session&lt;/h3&gt;<br />&lt;p&gt;Your session has expired, because you were idle too long.  You will have to log back into the system to continue what you were doing.&lt;/p&gt;'));
define("FILE_DEFAULT_MODE_STR",'0600');
define("DIR_DEFAULT_MODE_STR",'0777');
define("NONSSL_URL",'http://my.domain/');
define("SSL_URL",'https://my.domain/');
define("WORKFLOW_REVISION_LIMIT",'');
define("USER_REGISTRATION_NOTIF_SUBJECT",'New User Registration From Website');
define("USER_REGISTRATION_ADMIN_EMAIL",'');
define("USER_REGISTRATION_WELCOME_SUBJECT",'Welcome to our website!');
define("USER_REGISTRATION_WELCOME_MSG",'');
define("DISPLAY_THEME_REAL",'coolwatertheme');
define("DISPLAY_ATTRIBUTION",'username');
define("DISPLAY_DATETIME_FORMAT",'%A, %B %e, %l:%M%p');
define("DISPLAY_DATE_FORMAT",'%D');
define("DISPLAY_TIME_FORMAT",'%l:%M%p');
define("DISPLAY_START_OF_WEEK",'0');
define("DISPLAY_DEFAULT_TIMEZONE",'');
define("LDAP_SERVER",'not_configured');
define("LDAP_BASE_DN",'not_configured');
define("LDAP_BIND_USER",'not_configured');
define("LDAP_BIND_PASS",'not_configured');
define("SMTP_SERVER",'localhost');
define("SMTP_PORT",'25');
define("SMTP_AUTHTYPE",'NONE');
define("SMTP_USERNAME",'');
define("SMTP_PASSWORD",'');
define("SMTP_FROMADDRESS",'website@localhost');
define("MAINTENANCE_MSG_HTML",exponent_unhtmlentities('&lt;p&gt;This site is currently down for maintenance.&lt;/p&gt;'));
define("SESSION_TIMEOUT_ENABLE",1);
define("ENABLE_SSL",0);
define("ENABLE_WORKFLOW",0);
define("SITE_ALLOW_REGISTRATION",0);
define("SITE_USE_CAPTCHA",1);
define("USER_REGISTRATION_SEND_NOTIF",0);
define("USER_REGISTRATION_SEND_WELCOME",0);
define("USE_LDAP",0);
define("SMTP_USE_PHP_MAIL",0);
define("MAINTENANCE_MODE",0);
define("SEF_URLS",1);

?>