<?php
# Autogenerated for testing

define('TR_DATABASE_DBTYPE','XXXXXXX');
define('TR_DATABASE_HOST','XXXXXXX');
define('TR_DATABASE_PORT','XXXXXXX');
define('TR_DATABASE_DBNAME','XXXXXXX');
define('TR_DATABASE_USER','XXXXXXX');
define('TR_DATABASE_PWD','XXXXXXX');

?>
